/**
 * Canonical Tool Contract Registry — Phase 1 deliverable.
 *
 * Single source of truth for all FarmDash MCP tools. Generated artifacts
 * (tool-capabilities.generated.ts, mcp.json manifest) derive FROM this file.
 *
 * @generated-from scripts/enrich-mcp-manifest.mjs
 * @see docs/superpowers/specs/2026-09-16-api-intelligence-composition-design.md
 */

// --- Enums (narrow, typed) ---

export enum ToolAuthority {
  FARMDASH_READ_ONLY = 'FARMDASH_READ_ONLY',
  FARMDASH_ANALYZES = 'FARMDASH_ANALYZES',
  FARMDASH_PREPARES = 'FARMDASH_PREPARES',
  USER_SIGNS = 'USER_SIGNS',
  USER_SUBMITS = 'USER_SUBMITS',
  DELEGATED_SIGNER = 'DELEGATED_SIGNER',
  PROVIDER_EXECUTES = 'PROVIDER_EXECUTES',
  OPERATOR_ONLY = 'OPERATOR_ONLY',
}

export enum FinancialEffect {
  NONE = 'NONE',
  QUOTED_ONLY = 'QUOTED_ONLY',
  PREPARATION_ONLY = 'PREPARATION_ONLY',
  CUSTOMER_SIGNED_SPEND = 'CUSTOMER_SIGNED_SPEND',
  PROVIDER_FEE = 'PROVIDER_FEE',
  API_PAYMENT = 'API_PAYMENT',
  REVENUE_OBSERVATION = 'REVENUE_OBSERVATION',
}

export enum EvidenceClass {
  OBSERVED = 'OBSERVED',
  DERIVED = 'DERIVED',
  EDITORIAL = 'EDITORIAL',
  STALE = 'STALE',
  UNAVAILABLE = 'UNAVAILABLE',
  CALLER_ASSERTED = 'CALLER_ASSERTED',
  PROVIDER_VERIFIED = 'PROVIDER_VERIFIED',
  /** Cryptographic signature verification (EIP-191/EIP-712) WITHOUT chain settlement. */
  SIGNATURE_VERIFIED = 'SIGNATURE_VERIFIED',
  /** Evidence actually established from chain state (transaction hashes, receipts). */
  ONCHAIN_VERIFIED = 'ONCHAIN_VERIFIED',
}

// --- Tool contract shape ---

export interface ToolContract {
  toolName: string;
  apiRoute: string;
  featureStatusId: string;
  capabilityFamily: string;
  integrationRoles: string[];
  availability: string;
  tier: string;
  authority: ToolAuthority;
  financialEffect: FinancialEffect;
  inputArtifacts: string[];
  outputArtifacts: string[];
  prerequisites: string[];
  freshnessRequirements: string;
  userConfirmationRequirement: boolean;
  walletSignatureRequirement: boolean;
  submissionOwner: 'USER' | 'PROVIDER' | 'OPERATOR' | 'NONE';
  idempotencySemantics: 'IDEMPOTENT' | 'NOT_IDEMPOTENT' | 'SESSION_BOUND';
  nextTools: string[];
  blockedAlternatives: string[];
  evidenceClasses: EvidenceClass[];
  commercialModel: string;
}

// --- Capability family map ---

export const CAPABILITY_FAMILIES: Record<string, {
  label: string;
  description: string;
}> = {
  agent_core: { label: 'Agent Core', description: 'Agent bootstrap and onboarding.' },
  agent_execution: { label: 'Intent Lifecycle', description: 'FarmDashIntent create → approve → prepare → observe.' },
  trail_heat: { label: 'Trail Heat', description: 'Canonical live scores and editorial/catalog intelligence.' },
  protocol_intelligence: { label: 'Protocol Intelligence', description: 'Catalog metadata, risk factors, chain breakdown, and events.' },
  wallet: { label: 'Wallet & Portfolio', description: 'Balance, position, and capital reads.' },
  workflows: { label: 'Workflows', description: 'Planning, run, and capital route discovery.' },
  swap: { label: 'Swap', description: 'Quote, simulation, compatibility routing. Zero custody.' },
  swap_fee: { label: 'Swap Fee Settlement', description: 'Fee confirmation and settlement evidence.' },
  agent_planning: { label: 'Agent Planning', description: 'Research, optimization, yield comparison.' },
  futures: { label: 'Futures / Hyperliquid', description: 'Perp accounts, strategies, positions.' },
  ledger: { label: 'Ledger & Performance', description: 'Realized PnL, tax, performance, reputation.' },
  security: { label: 'Security Preflight', description: 'Allowance risk, transaction risk audits.' },
  autonomous_operator: { label: 'Autonomous Operator', description: 'Sessions, keys, event streams.' },
  autonomous_operator_erc4337: { label: 'ERC-4337 Submission', description: 'Session keys and UserOperation lifecycle (preview-only).' },
  mee_cross_chain: { label: 'MEE Cross-Chain', description: 'Multi-Exit-Execution cross-chain intent bundles (preparation-only).' },
  virtuals_acp: { label: 'Virtuals ACP', description: 'Tenant-owned tenders and specialist hiring.' },
};

// --- Tool contracts (79 unique tools) ---

export const TOOL_CONTRACTS: Readonly<Record<string, ToolContract>> = {
  // === agent_core ===
  agent_onboard: {
    toolName: 'agent_onboard',
    apiRoute: '/api/v1/agent/status',
    featureStatusId: 'agent_core.bootstrap',
    capabilityFamily: 'agent_core',
    integrationRoles: ['agent_core'],
    availability: 'available',
    tier: 'scout',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['agentStatus'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['create_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === agent_execution.intent_lifecycle (13 tools) ===
  create_intent: {
    toolName: 'create_intent',
    apiRoute: '/api/v1/agent/intents/create',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken', 'FarmDashIntent'],
    outputArtifacts: ['intentId'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['policy_check_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  policy_check_intent: {
    toolName: 'policy_check_intent',
    apiRoute: '/api/v1/agent/intents/{intentId}/policy-check',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['policy', 'intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'policy', 'context'],
    outputArtifacts: ['policyResult'],
    prerequisites: ['create_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['simulate_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  simulate_intent: {
    toolName: 'simulate_intent',
    apiRoute: '/api/v1/agent/intents/{intentId}/simulate',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['simulation', 'intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'simulation'],
    outputArtifacts: ['simulationResult'],
    prerequisites: ['create_intent', 'policy_check_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['request_approval_payload'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  request_approval_payload: {
    toolName: 'request_approval_payload',
    apiRoute: '/api/v1/agent/intents/{intentId}/approval-payload',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['approval', 'eip712'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'approverAddress', 'decision'],
    outputArtifacts: ['eip712Payload'],
    prerequisites: ['simulate_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['request_human_approval'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  request_human_approval: {
    toolName: 'request_human_approval',
    apiRoute: '/api/v1/agent/intents/{intentId}/approve',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['approval', 'human'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'approverAddress'],
    outputArtifacts: ['approvalStatus'],
    prerequisites: ['request_approval_payload'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: false,
    submissionOwner: 'USER',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['submit_signed_approval'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.CALLER_ASSERTED],
    commercialModel: 'NONE',
  },
  submit_signed_approval: {
    toolName: 'submit_signed_approval',
    apiRoute: '/api/v1/agent/intents/{intentId}/approve',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['approval', 'eip712', 'submission'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'signedApproval'],
    outputArtifacts: ['approvalConfirmation'],
    prerequisites: ['request_human_approval'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['prepare_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: 'NONE',
  },
  get_approval_status: {
    toolName: 'get_approval_status',
    apiRoute: '/api/v1/agent/intents/{intentId}',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['approval', 'status'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId'],
    outputArtifacts: ['approvalState'],
    prerequisites: ['create_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['submit_signed_approval'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  prepare_intent: {
    toolName: 'prepare_intent',
    apiRoute: '/api/v1/agent/intents/{intentId}/prepare',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['preparation', 'intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ['intentId', 'signedApproval'],
    outputArtifacts: ['preparedCalldata'],
    prerequisites: ['submit_signed_approval'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['execute_approved_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  execute_approved_intent: {
    toolName: 'execute_approved_intent',
    apiRoute: '/api/v1/agent/intents/{intentId}/execute',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['execution', 'intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.USER_SUBMITS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['intentId', 'preparedCalldata'],
    outputArtifacts: ['transactionHash'],
    prerequisites: ['prepare_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['confirm_execution'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },
  confirm_execution: {
    toolName: 'confirm_execution',
    apiRoute: '/api/v1/agent/intents/{intentId}/execute',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['confirmation', 'receipt'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId', 'transactionHash'],
    outputArtifacts: ['receipt'],
    prerequisites: ['execute_approved_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['get_receipt'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },
  get_receipt: {
    toolName: 'get_receipt',
    apiRoute: '/api/v1/agent/receipts/{receiptId}',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['receipt', 'settlement'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['receiptId'],
    outputArtifacts: ['receipt'],
    prerequisites: ['execute_approved_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },
  get_agent_activity: {
    toolName: 'get_agent_activity',
    apiRoute: '/api/v1/agent/receipts',
    featureStatusId: 'agent_execution.intent_lifecycle',
    capabilityFamily: 'agent_execution',
    integrationRoles: ['activity', 'history'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['activityList'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === trail_heat (12 tools) — MISCLASSIFIED: should move to own family ===
  get_trail_heat: {
    toolName: 'get_trail_heat',
    apiRoute: '/api/v1/trail-heat',
    featureStatusId: 'trail_heat.live_scores',
    capabilityFamily: 'trail_heat',
    integrationRoles: ['trail_heat', 'live_scores'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['trailHeatScores'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_protocol_metadata: {
    toolName: 'get_protocol_metadata',
    apiRoute: '/api/v1/agent/protocols',
    featureStatusId: 'protocol_intelligence.metadata',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['protocols', 'metadata'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['protocolMetadata'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['get_protocol_risk_factors'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_protocol_risk_factors: {
    toolName: 'get_protocol_risk_factors',
    apiRoute: '/api/v1/agent/protocols',
    featureStatusId: 'protocol_intelligence.risk',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['protocols', 'risk'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['riskFactors'],
    prerequisites: ['get_protocol_metadata'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  get_chain_breakdown: {
    toolName: 'get_chain_breakdown',
    apiRoute: '/api/v1/agent/chain-breakdown',
    featureStatusId: 'protocol_intelligence.chain',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['chains', 'breakdown'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['chainBreakdown'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_agent_events: {
    toolName: 'get_agent_events',
    apiRoute: '/api/v1/agent/events',
    featureStatusId: 'protocol_intelligence.events',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['events', 'agent'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['eventList'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  audit_sybil_risk: {
    toolName: 'audit_sybil_risk',
    apiRoute: '/api/v1/agent/sybil-audit',
    featureStatusId: 'protocol_intelligence.sybil',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['sybil', 'audit'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['sybilAudit'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  simulate_points: {
    toolName: 'simulate_points',
    apiRoute: '/api/v1/agent/simulate-points',
    featureStatusId: 'protocol_intelligence.points',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['points', 'simulation'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['pointsSimulation'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  get_historical_trailheat: {
    toolName: 'get_historical_trailheat',
    apiRoute: '/api/v1/agent/historical-trailheat',
    featureStatusId: 'trail_heat.historical',
    capabilityFamily: 'trail_heat',
    integrationRoles: ['trail_heat', 'historical'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['historicalTrailHeat'],
    prerequisites: [],
    freshnessRequirements: '7d',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_token_prices: {
    toolName: 'get_token_prices',
    apiRoute: '/api/v1/agent/prices',
    featureStatusId: 'protocol_intelligence.prices',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['prices', 'tokens'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['tokenPrices'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  analyze_protocol_risk: {
    toolName: 'analyze_protocol_risk',
    apiRoute: '/api/v1/agent/protocol-risk',
    featureStatusId: 'protocol_intelligence.risk',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['protocols', 'risk_analysis'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['riskAnalysis'],
    prerequisites: ['get_protocol_metadata'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  simulate_yield_strategy: {
    toolName: 'simulate_yield_strategy',
    apiRoute: '/api/v1/agent/simulate-yield',
    featureStatusId: 'protocol_intelligence.yield',
    capabilityFamily: 'protocol_intelligence',
    integrationRoles: ['yield', 'simulation'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['yieldSimulation'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  query_trail_heat: {
    toolName: 'query_trail_heat',
    apiRoute: '/api/v1/agent/trail-heat-query',
    featureStatusId: 'trail_heat.query',
    capabilityFamily: 'trail_heat',
    integrationRoles: ['trail_heat', 'query'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['filteredTrailHeat'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === wallet.portfolio_reads (4 tools) ===
  get_wallet_balances: {
    toolName: 'get_wallet_balances',
    apiRoute: '/api/v1/agent/balances',
    featureStatusId: 'wallet.portfolio_reads',
    capabilityFamily: 'wallet',
    integrationRoles: ['balances', 'wallet'],
    availability: 'paid_ready',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['balances'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_portfolio_summary: {
    toolName: 'get_portfolio_summary',
    apiRoute: '/api/v1/agent/balances',
    featureStatusId: 'wallet.portfolio_reads',
    capabilityFamily: 'wallet',
    integrationRoles: ['portfolio', 'summary'],
    availability: 'paid_ready',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['portfolioSummary'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_position_health: {
    toolName: 'get_position_health',
    apiRoute: '/api/v1/agent/performance',
    featureStatusId: 'wallet.portfolio_reads',
    capabilityFamily: 'wallet',
    integrationRoles: ['positions', 'health'],
    availability: 'paid_ready',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['positionHealth'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_idle_capital: {
    toolName: 'get_idle_capital',
    apiRoute: '/api/v1/agent/balances',
    featureStatusId: 'wallet.portfolio_reads',
    capabilityFamily: 'wallet',
    integrationRoles: ['capital', 'idle'],
    availability: 'paid_ready',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['idleCapital'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === workflows.supervised (4 tools) ===
  list_workflows: {
    toolName: 'list_workflows',
    apiRoute: '/api/v1/agent/workflows',
    featureStatusId: 'workflows.supervised',
    capabilityFamily: 'workflows',
    integrationRoles: ['workflows', 'list'],
    availability: 'available_with_tier_gate',
    tier: 'scout_catalog_pioneer_runs',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['workflowList'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['plan_workflow'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  plan_workflow: {
    toolName: 'plan_workflow',
    apiRoute: '/api/v1/agent/workflows',
    featureStatusId: 'workflows.supervised',
    capabilityFamily: 'workflows',
    integrationRoles: ['workflows', 'plan'],
    availability: 'available_with_tier_gate',
    tier: 'scout_catalog_pioneer_runs',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken', 'params'],
    outputArtifacts: ['workflowPlan'],
    prerequisites: ['list_workflows'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['run_workflow'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  run_workflow: {
    toolName: 'run_workflow',
    apiRoute: '/api/v1/agent/workflows',
    featureStatusId: 'workflows.supervised',
    capabilityFamily: 'workflows',
    integrationRoles: ['workflows', 'run'],
    availability: 'available_with_tier_gate',
    tier: 'scout_catalog_pioneer_runs',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ['sessionToken', 'workflowPlan'],
    outputArtifacts: ['workflowRun'],
    prerequisites: ['plan_workflow'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['get_workflow_status'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  get_workflow_status: {
    toolName: 'get_workflow_status',
    apiRoute: '/api/v1/agent/workflows',
    featureStatusId: 'workflows.supervised',
    capabilityFamily: 'workflows',
    integrationRoles: ['workflows', 'status'],
    availability: 'available_with_tier_gate',
    tier: 'scout_catalog_pioneer_runs',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken', 'workflowRun'],
    outputArtifacts: ['runStatus'],
    prerequisites: ['run_workflow'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === swap.compatibility_evm (5 tools) ===
  find_capital_route: {
    toolName: 'find_capital_route',
    apiRoute: '/api/v1/agent/routes',
    featureStatusId: 'swap.compatibility_evm',
    capabilityFamily: 'swap',
    integrationRoles: ['swap', 'routing', 'capital'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['fromToken', 'toToken', 'amount'],
    outputArtifacts: ['route'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['get_swap_quote'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_swap_quote: {
    toolName: 'get_swap_quote',
    apiRoute: '/api/v1/agent/quote-intent',
    featureStatusId: 'swap.compatibility_evm',
    capabilityFamily: 'swap',
    integrationRoles: ['swap', 'quote', 'lifi', 'relay', 'zerox'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.QUOTED_ONLY,
    inputArtifacts: ['fromToken', 'toToken', 'amount', 'slippage'],
    outputArtifacts: ['quote', 'simulationIntent'],
    prerequisites: ['find_capital_route'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['simulate_swap_execution'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'PROVIDER_FEE',
  },
  simulate_swap_execution: {
    toolName: 'simulate_swap_execution',
    apiRoute: '/api/v1/simulate',
    featureStatusId: 'swap.compatibility_evm',
    capabilityFamily: 'swap',
    integrationRoles: ['swap', 'simulation'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.QUOTED_ONLY,
    inputArtifacts: ['quote'],
    outputArtifacts: ['simulationResult'],
    prerequisites: ['get_swap_quote'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['execute_swap'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  execute_swap: {
    toolName: 'execute_swap',
    apiRoute: '/api/agents/swap',
    featureStatusId: 'swap.compatibility_evm',
    capabilityFamily: 'swap',
    integrationRoles: ['swap', 'execution'],
    availability: 'preparation_only',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.USER_SUBMITS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['quote', 'simulationResult'],
    outputArtifacts: ['transactionHash'],
    prerequisites: ['simulate_swap_execution'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['confirm_swap'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'PROVIDER_FEE',
  },
  confirm_swap: {
    toolName: 'confirm_swap',
    apiRoute: '/api/agents/confirm',
    featureStatusId: 'swap_fee_settlement_confirmation',
    capabilityFamily: 'swap_fee',
    integrationRoles: ['swap', 'confirmation', 'fee'],
    availability: 'preparation_only',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.PROVIDER_FEE,
    inputArtifacts: ['transactionHash'],
    outputArtifacts: ['receipt', 'feeEvidence'],
    prerequisites: ['execute_swap'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'PROVIDER_FEE',
  },

  // === agent_planning (4 tools) ===
  optimize_portfolio: {
    toolName: 'optimize_portfolio',
    apiRoute: '/api/v1/agent/optimize',
    featureStatusId: 'agent_planning.research',
    capabilityFamily: 'agent_planning',
    integrationRoles: ['portfolio', 'optimization'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['optimization'],
    prerequisites: ['get_portfolio_summary'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  resolve_defi_intent: {
    toolName: 'resolve_defi_intent',
    apiRoute: '/api/v1/agent/defi',
    featureStatusId: 'agent_planning.research',
    capabilityFamily: 'agent_planning',
    integrationRoles: ['defi', 'intent_resolution'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['naturalLanguageIntent'],
    outputArtifacts: ['resolvedIntent'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['create_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  run_risk_sentinel: {
    toolName: 'run_risk_sentinel',
    apiRoute: '/api/v1/agent/risk-sentinel',
    featureStatusId: 'agent_planning.research',
    capabilityFamily: 'agent_planning',
    integrationRoles: ['risk', 'sentinel'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['intentId'],
    outputArtifacts: ['riskAssessment'],
    prerequisites: ['create_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['simulate_swap_execution'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  compare_yields: {
    toolName: 'compare_yields',
    apiRoute: '/api/v1/agent/compare-yields',
    featureStatusId: 'agent_planning.research',
    capabilityFamily: 'agent_planning',
    integrationRoles: ['yield', 'comparison'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['yieldComparison'],
    prerequisites: [],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  recommend_delta_hedge: {
    toolName: 'recommend_delta_hedge',
    apiRoute: '/api/v1/agent/hedge',
    featureStatusId: 'agent_planning.research',
    capabilityFamily: 'agent_planning',
    integrationRoles: ['hedge', 'recommendation'],
    availability: 'available',
    tier: 'scout_preview_pioneer_full',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['positionId'],
    outputArtifacts: ['hedgeRecommendation'],
    prerequisites: ['get_position_health'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },

  // === futures.hyperliquid_guarded (7 tools) ===
  scan_funding_rates: {
    toolName: 'scan_funding_rates',
    apiRoute: '/api/v1/agent/funding-rates',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['funding_rates', 'hyperliquid'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['fundingRates'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  scan_market_conditions: {
    toolName: 'scan_market_conditions',
    apiRoute: '/api/v1/agent/market-conditions',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['market_conditions', 'hyperliquid'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['marketConditions'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_futures_account: {
    toolName: 'get_futures_account',
    apiRoute: '/api/v1/agent/futures',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['futures', 'account'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['futuresAccount'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  analyze_futures_strategy: {
    toolName: 'analyze_futures_strategy',
    apiRoute: '/api/v1/agent/futures-strategy',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['futures', 'strategy'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ['strategyAnalysis'],
    prerequisites: ['get_futures_account'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  calculate_position_size: {
    toolName: 'calculate_position_size',
    apiRoute: '/api/v1/agent/position-size',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['position_size', 'calculation'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['riskParams'],
    outputArtifacts: ['positionSize'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  execute_perp_order: {
    toolName: 'execute_perp_order',
    apiRoute: '/api/v1/agent/perps',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['perps', 'execution'],
    availability: 'preparation_only',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SUBMITS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['orderParams'],
    outputArtifacts: ['transactionHash'],
    prerequisites: ['calculate_position_size'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },
  cancel_perp_order: {
    toolName: 'cancel_perp_order',
    apiRoute: '/api/v1/agent/perps',
    featureStatusId: 'futures.hyperliquid_guarded',
    capabilityFamily: 'futures',
    integrationRoles: ['perps', 'cancel'],
    availability: 'preparation_only',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SUBMITS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['orderId'],
    outputArtifacts: ['cancelConfirmation'],
    prerequisites: ['execute_perp_order'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },

  // === ledger.activity (4 tools) ===
  get_agent_performance: {
    toolName: 'get_agent_performance',
    apiRoute: '/api/v1/agent/performance',
    featureStatusId: 'ledger.activity',
    capabilityFamily: 'ledger',
    integrationRoles: ['performance', 'agent'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['performance'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: '7d',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  ledger_realized_pnl: {
    toolName: 'ledger_realized_pnl',
    apiRoute: '/api/v1/agent/ledger/pnl',
    featureStatusId: 'ledger.activity',
    capabilityFamily: 'ledger',
    integrationRoles: ['ledger', 'pnl', 'realized'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.REVENUE_OBSERVATION,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['realizedPnl'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: '7d',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'REVENUE_OBSERVATION',
  },
  ledger_tax_export: {
    toolName: 'ledger_tax_export',
    apiRoute: '/api/v1/agent/ledger/tax',
    featureStatusId: 'ledger.activity',
    capabilityFamily: 'ledger',
    integrationRoles: ['ledger', 'tax', 'export'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.REVENUE_OBSERVATION,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['taxExport'],
    prerequisites: ['ledger_realized_pnl'],
    freshnessRequirements: '30d',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'REVENUE_OBSERVATION',
  },

  // === security.preflight (2 tools) ===
  audit_allowance_risk: {
    toolName: 'audit_allowance_risk',
    apiRoute: '/api/v1/agent/allowance-audit',
    featureStatusId: 'security.preflight',
    capabilityFamily: 'security',
    integrationRoles: ['allowance', 'audit'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['allowanceRisk'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: '24h',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  simulate_transaction_risk: {
    toolName: 'simulate_transaction_risk',
    apiRoute: '/api/v1/agent/transaction-risk',
    featureStatusId: 'security.preflight',
    capabilityFamily: 'security',
    integrationRoles: ['transaction', 'risk', 'simulation'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['transactionHash'],
    outputArtifacts: ['riskSimulation'],
    prerequisites: [],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },

  // === autonomous_operator.sessions (7 tools) ===
  create_session: {
    toolName: 'create_session',
    apiRoute: '/api/v1/agent/sessions',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['session', 'creation'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['sessionId'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['session_heartbeat'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  session_heartbeat: {
    toolName: 'session_heartbeat',
    apiRoute: '/api/v1/agent/sessions',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['session', 'heartbeat'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['heartbeat'],
    prerequisites: ['create_session'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['configure_autopilot'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_farming_context: {
    toolName: 'get_farming_context',
    apiRoute: '/api/v1/agent/farming-context',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['farming_context', 'memory'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['farmingContext'],
    prerequisites: ['sessionId'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['patch_farming_context'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  patch_farming_context: {
    toolName: 'patch_farming_context',
    apiRoute: '/api/v1/agent/farming-context',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['farming_context', 'patch'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId', 'patch'],
    outputArtifacts: ['farmingContext'],
    prerequisites: ['get_farming_context'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  get_event_stream_snapshot: {
    toolName: 'get_event_stream_snapshot',
    apiRoute: '/api/v1/agent/events/snapshot',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['events', 'snapshot'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['eventSnapshot'],
    prerequisites: ['sessionId'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  verify_delegation: {
    toolName: 'verify_delegation',
    apiRoute: '/api/v1/agent/delegation',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['delegation', 'verify'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['delegationProof'],
    prerequisites: ['sessionId'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  configure_autopilot: {
    toolName: 'configure_autopilot',
    apiRoute: '/api/v1/agent/autopilot',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['autopilot', 'configuration'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId', 'config'],
    outputArtifacts: ['autopilotConfig'],
    prerequisites: ['session_heartbeat'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['autopilot_cycle'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === autonomous_operator.erc4337_submission (4 tools) ===
  grant_session_key: {
    toolName: 'grant_session_key',
    apiRoute: '/api/v1/agent/session-keys',
    featureStatusId: 'autonomous_operator.erc4337_submission',
    capabilityFamily: 'autonomous_operator_erc4337',
    integrationRoles: ['session_key', 'grant', 'erc4337'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.DELEGATED_SIGNER,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId', 'grantParams'],
    outputArtifacts: ['sessionKeyGrant'],
    prerequisites: ['create_session'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['autopilot_cycle'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: 'NONE',
  },
  revoke_session_key: {
    toolName: 'revoke_session_key',
    apiRoute: '/api/v1/agent/session-keys',
    featureStatusId: 'autonomous_operator.erc4337_submission',
    capabilityFamily: 'autonomous_operator_erc4337',
    integrationRoles: ['session_key', 'revoke', 'erc4337'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['revokeConfirmation'],
    prerequisites: ['create_session'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: 'NONE',
  },
  session_key_status: {
    toolName: 'session_key_status',
    apiRoute: '/api/v1/agent/session-keys',
    featureStatusId: 'autonomous_operator.erc4337_submission',
    capabilityFamily: 'autonomous_operator_erc4337',
    integrationRoles: ['session_key', 'status'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['keyStatus'],
    prerequisites: ['create_session'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === autonomous_operator (2 tools) ===
  autopilot_cycle: {
    toolName: 'autopilot_cycle',
    apiRoute: '/api/v1/agent/autopilot/cycle',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['autopilot', 'cycle'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ['sessionId', 'autopilotConfig'],
    outputArtifacts: ['cycleResult'],
    prerequisites: ['configure_autopilot'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['pause_autopilot'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.PROVIDER_VERIFIED],
    commercialModel: 'NONE',
  },
  pause_autopilot: {
    toolName: 'pause_autopilot',
    apiRoute: '/api/v1/agent/autopilot',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['autopilot', 'pause'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['pauseConfirmation'],
    prerequisites: ['autopilot_cycle'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: false,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['resume_autopilot'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  resume_autopilot: {
    toolName: 'resume_autopilot',
    apiRoute: '/api/v1/agent/autopilot',
    featureStatusId: 'autonomous_operator.sessions',
    capabilityFamily: 'autonomous_operator',
    integrationRoles: ['autopilot', 'resume'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionId'],
    outputArtifacts: ['resumeConfirmation'],
    prerequisites: ['pause_autopilot'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: false,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === mee_cross_chain (4 tools) ===
  create_mee_intent: {
    toolName: 'create_mee_intent',
    apiRoute: '/api/v1/agent/mee',
    featureStatusId: 'agent_execution.mee_cross_chain',
    capabilityFamily: 'mee_cross_chain',
    integrationRoles: ['mee', 'cross_chain', 'intent'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ['sessionToken', 'meeParams'],
    outputArtifacts: ['meeIntent'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['simulate_mee_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  simulate_mee_intent: {
    toolName: 'simulate_mee_intent',
    apiRoute: '/api/v1/agent/mee',
    featureStatusId: 'agent_execution.mee_cross_chain',
    capabilityFamily: 'mee_cross_chain',
    integrationRoles: ['mee', 'simulation'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.QUOTED_ONLY,
    inputArtifacts: ['meeIntent'],
    outputArtifacts: ['meeSimulation'],
    prerequisites: ['create_mee_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['submit_mee_intent'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  submit_mee_intent: {
    toolName: 'submit_mee_intent',
    apiRoute: '/api/v1/agent/mee',
    featureStatusId: 'agent_execution.mee_cross_chain',
    capabilityFamily: 'mee_cross_chain',
    integrationRoles: ['mee', 'submission'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.USER_SUBMITS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['meeIntent', 'meeSimulation'],
    outputArtifacts: ['submissionReceipt'],
    prerequisites: ['simulate_mee_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: ['get_mee_intent_status'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: 'NONE',
  },
  get_mee_intent_status: {
    toolName: 'get_mee_intent_status',
    apiRoute: '/api/v1/agent/mee',
    featureStatusId: 'agent_execution.mee_cross_chain',
    capabilityFamily: 'mee_cross_chain',
    integrationRoles: ['mee', 'status'],
    availability: 'preparation_only',
    tier: 'session_bound',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['meeIntentId'],
    outputArtifacts: ['meeStatus'],
    prerequisites: ['submit_mee_intent'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },

  // === virtuals_acp (5 tools) ===
  get_virtuals_tender: {
    toolName: 'get_virtuals_tender',
    apiRoute: '/api/v1/agent/virtuals',
    featureStatusId: 'virtuals_acp.tenant_owned_tenders',
    capabilityFamily: 'virtuals_acp',
    integrationRoles: ['virtuals', 'tender'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['sessionToken'],
    outputArtifacts: ['tender'],
    prerequisites: ['sessionToken'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['bind_virtuals_tender_job'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  cancel_virtuals_tender: {
    toolName: 'cancel_virtuals_tender',
    apiRoute: '/api/v1/agent/virtuals',
    featureStatusId: 'virtuals_acp.tenant_owned_tenders',
    capabilityFamily: 'virtuals_acp',
    integrationRoles: ['virtuals', 'cancel'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['tenderId'],
    outputArtifacts: ['cancelConfirmation'],
    prerequisites: ['get_virtuals_tender'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: false,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  bind_virtuals_tender_job: {
    toolName: 'bind_virtuals_tender_job',
    apiRoute: '/api/v1/agent/virtuals',
    featureStatusId: 'virtuals_acp.tenant_owned_tenders',
    capabilityFamily: 'virtuals_acp',
    integrationRoles: ['virtuals', 'bind', 'job'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['tenderId', 'jobParams'],
    outputArtifacts: ['jobBinding'],
    prerequisites: ['get_virtuals_tender'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['evaluate_virtuals_tender'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: 'NONE',
  },
  evaluate_virtuals_tender: {
    toolName: 'evaluate_virtuals_tender',
    apiRoute: '/api/v1/agent/virtuals',
    featureStatusId: 'virtuals_acp.tenant_owned_tenders',
    capabilityFamily: 'virtuals_acp',
    integrationRoles: ['virtuals', 'evaluate'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ['jobId'],
    outputArtifacts: ['evaluation'],
    prerequisites: ['bind_virtuals_tender_job'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: 'NONE',
    idempotencySemantics: 'IDEMPOTENT',
    nextTools: ['hire_virtuals_specialist'],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.DERIVED],
    commercialModel: 'NONE',
  },
  hire_virtuals_specialist: {
    toolName: 'hire_virtuals_specialist',
    apiRoute: '/api/v1/agent/virtuals',
    featureStatusId: 'virtuals_acp.tenant_owned_tenders',
    capabilityFamily: 'virtuals_acp',
    integrationRoles: ['virtuals', 'hire', 'specialist'],
    availability: 'available',
    tier: 'pioneer_plus',
    authority: ToolAuthority.PROVIDER_EXECUTES,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ['evaluationId'],
    outputArtifacts: ['hireConfirmation'],
    prerequisites: ['evaluate_virtuals_tender'],
    freshnessRequirements: 'live',
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: 'USER',
    idempotencySemantics: 'NOT_IDEMPOTENT',
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.ONCHAIN_VERIFIED],
    commercialModel: 'NONE',
  },

  // Audited against lib/api/agents/vouch.ts: requires EIP-191 signature over
  // "FARMDASH_VOUCH:<target>:<nonce>" and upserts agent_vouches. Scout-reachable,
  // economically gated by the vouch_sybil_gate (>=1 prior swap), no funds moved.
  vouch: {
    toolName: "vouch",
    apiRoute: "/api/agents/vouch",
    featureStatusId: "ledger.activity",
    capabilityFamily: "ledger",
    integrationRoles: ["vouch"],
    availability: "available",
    tier: "scout",
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ["vouchResult"],
    prerequisites: [],
    freshnessRequirements: "24h",
    userConfirmationRequirement: false,
    walletSignatureRequirement: true,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agents/history.ts: hard pioneer/syndicate gate with
  // wallet-bound API key (history.ts:41-53); tenant-isolated fee/revenue reads.
  history: {
    toolName: "history",
    apiRoute: "/api/agents/history",
    featureStatusId: "ledger.activity",
    capabilityFamily: "ledger",
    integrationRoles: ["history"],
    availability: "available_with_tier_gate",
    tier: "pioneer",
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.REVENUE_OBSERVATION,
    inputArtifacts: [],
    outputArtifacts: ["historyResult"],
    prerequisites: [],
    freshnessRequirements: "24h",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agents/quote.ts: provider-neutral estimate or
  // stored firm quote; never executes (execution_boundary, unsigned: true).
  quote: {
    toolName: "quote",
    apiRoute: "/api/agents/quote",
    featureStatusId: "swap.compatibility_evm",
    capabilityFamily: "swap",
    integrationRoles: ["quote"],
    availability: "available",
    tier: "scout",
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.QUOTED_ONLY,
    inputArtifacts: [],
    outputArtifacts: ["quoteResult"],
    prerequisites: [],
    freshnessRequirements: "live",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agents/register.ts: requires EIP-191 signature over
  // "FARMDASH_REGISTER_AGENT:<agentAddress>:<agentName>:<nonce>"; upserts
  // agent_registrations. Degrades 503 feature_not_ready when table missing.
  register: {
    toolName: "register",
    apiRoute: "/api/agents/register",
    featureStatusId: "agent_core.bootstrap",
    capabilityFamily: "agent_core",
    integrationRoles: ["register"],
    availability: "available",
    tier: "scout",
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: [],
    outputArtifacts: ["registerResult"],
    prerequisites: [],
    freshnessRequirements: "24h",
    userConfirmationRequirement: false,
    walletSignatureRequirement: true,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agent/autopilot.ts:66-68: hard syndicate gate
  // (402 otherwise) plus verified session access; pure status read over the
  // Redis-backed AutopilotJobQueue (503 degraded when queue unavailable).
  get_cycle_status: {
    toolName: "get_cycle_status",
    apiRoute: "/api/v1/agent/autopilot",
    featureStatusId: "autonomous_operator.erc4337_submission",
    capabilityFamily: "autonomous_operator_erc4337",
    integrationRoles: ["cycle", "status"],
    availability: "available",
    tier: "syndicate",
    authority: ToolAuthority.FARMDASH_READ_ONLY,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ["sessionId"],
    outputArtifacts: ["cycleStatus"],
    prerequisites: [],
    freshnessRequirements: "live",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "SESSION_BOUND",
    nextTools: [],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agent/autopilot.ts:397-408: fails closed
  // unconditionally (respondFeatureNotReady, reasonCode
  // 'autonomous_execution_preview_only'); AutonomousExecutor.isAvailable() is
  // hardcoded false. Never executes, never changes state, never broadcasts.
  execute_cycle_actions: {
    toolName: "execute_cycle_actions",
    apiRoute: "/api/v1/agent/autopilot",
    featureStatusId: "autonomous_operator.erc4337_submission",
    capabilityFamily: "autonomous_operator_erc4337",
    integrationRoles: ["cycle", "execution"],
    availability: "unavailable_preview_only",
    tier: "syndicate",
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ["sessionId"],
    outputArtifacts: ["cycleActionsResult"],
    prerequisites: [],
    freshnessRequirements: "live",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: [],
    blockedAlternatives: ["get_cycle_status"],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agent/virtuals-acp.ts:588-614: scout pays x402
  // (402) or holds a paid tier, plus session, ACP V2 rollout gates and 9
  // readiness checks. Selection only: spend_authority 'none_selection_only'.
  select_virtuals_provider_plan_v2: {
    toolName: "select_virtuals_provider_plan_v2",
    apiRoute: "/api/v1/agent/virtuals-acp",
    featureStatusId: "virtuals_acp.tenant_owned_tenders",
    capabilityFamily: "virtuals_acp",
    integrationRoles: ["virtuals", "plan"],
    availability: "available_with_tier_gate",
    tier: "x402_or_subscription_with_authenticated_session",
    authority: ToolAuthority.FARMDASH_ANALYZES,
    financialEffect: FinancialEffect.NONE,
    inputArtifacts: ["sessionId"],
    outputArtifacts: ["planSelection"],
    prerequisites: [],
    freshnessRequirements: "live",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: ["prepare_virtuals_tender_v2"],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agent/virtuals-acp.ts:802-893: verifies a fresh
  // EIP-712 user approval signature and consumes a single-use nonce, then
  // records the tenant-owned tender authorization. FarmDash never moves funds;
  // the committed spend is CUSTOMER_SIGNED_SPEND performed by the customer
  // connector. Requires an unconsumed prepared tender.
  authorize_virtuals_tender_v2: {
    toolName: "authorize_virtuals_tender_v2",
    apiRoute: "/api/v1/agent/virtuals-acp",
    featureStatusId: "virtuals_acp.tenant_owned_tenders",
    capabilityFamily: "virtuals_acp",
    integrationRoles: ["virtuals", "authorize"],
    availability: "available_with_tier_gate",
    tier: "x402_or_subscription_with_authenticated_session",
    authority: ToolAuthority.USER_SIGNS,
    financialEffect: FinancialEffect.CUSTOMER_SIGNED_SPEND,
    inputArtifacts: ["sessionId", "preparedTender", "signature"],
    outputArtifacts: ["authorization"],
    prerequisites: ["prepare_virtuals_tender_v2"],
    freshnessRequirements: "live",
    userConfirmationRequirement: true,
    walletSignatureRequirement: true,
    submissionOwner: "USER",
    idempotencySemantics: "NOT_IDEMPOTENT",
    nextTools: ["get_virtuals_tender"],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.SIGNATURE_VERIFIED],
    commercialModel: "NONE",
  },
  // Audited against lib/api/agent/virtuals-acp.ts:616-730: creates a
  // non-spendable V2 draft tender and returns EIP-712 approval_typed_data for
  // LOCAL user signing (spend_authority 'none_draft_only'). Consumes a plan
  // selection; response cannot create or fund a job.
  prepare_virtuals_tender_v2: {
    toolName: "prepare_virtuals_tender_v2",
    apiRoute: "/api/v1/agent/virtuals-acp",
    featureStatusId: "virtuals_acp.tenant_owned_tenders",
    capabilityFamily: "virtuals_acp",
    integrationRoles: ["virtuals", "prepare"],
    availability: "available_with_tier_gate",
    tier: "x402_or_subscription_with_authenticated_session",
    authority: ToolAuthority.FARMDASH_PREPARES,
    financialEffect: FinancialEffect.PREPARATION_ONLY,
    inputArtifacts: ["sessionId", "planSelection"],
    prerequisites: ["select_virtuals_provider_plan_v2"],
    outputArtifacts: ["preparedTender"],
    freshnessRequirements: "live",
    userConfirmationRequirement: false,
    walletSignatureRequirement: false,
    submissionOwner: "NONE",
    idempotencySemantics: "IDEMPOTENT",
    nextTools: ["authorize_virtuals_tender_v2"],
    blockedAlternatives: [],
    evidenceClasses: [EvidenceClass.OBSERVED],
    commercialModel: "NONE",
  },
};

// --- Helpers ---

export function getToolContract(name: string): ToolContract {
  const contract = TOOL_CONTRACTS[name];
  if (!contract) throw new Error(`Missing tool contract for ${name}`);
  return contract;
}

export function getContractByFamily(family: string): ToolContract[] {
  return Object.values(TOOL_CONTRACTS).filter(c => c.capabilityFamily === family);
}

export function getAllToolNames(): string[] {
  return Object.keys(TOOL_CONTRACTS);
}

export function getContractCount(): number {
  return Object.keys(TOOL_CONTRACTS).length;
}
