// Generated by scripts/enrich-mcp-manifest.mjs. Do not edit by hand.
export interface McpToolCapability {
  api_route: string;
  feature_status_id: string;
  availability: string;
  tier: string;
  status_endpoint: string;
}

export const MCP_TOOL_CAPABILITIES: Readonly<Record<string, McpToolCapability>> = {
  "agent_onboard": {
    "api_route": "/api/v1/agent/status",
    "feature_status_id": "agent_core.bootstrap",
    "availability": "available",
    "tier": "scout",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "create_intent": {
    "api_route": "/api/v1/agent/intents/create",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "policy_check_intent": {
    "api_route": "/api/v1/agent/intents/{intentId}/policy-check",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_intent": {
    "api_route": "/api/v1/agent/intents/{intentId}/simulate",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "request_approval_payload": {
    "api_route": "/api/v1/agent/intents/{intentId}/approval-payload",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "request_human_approval": {
    "api_route": "/api/v1/agent/intents/{intentId}/approve",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "submit_signed_approval": {
    "api_route": "/api/v1/agent/intents/{intentId}/approve",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_approval_status": {
    "api_route": "/api/v1/agent/intents/{intentId}",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "prepare_intent": {
    "api_route": "/api/v1/agent/intents/{intentId}/prepare",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "execute_approved_intent": {
    "api_route": "/api/v1/agent/intents/{intentId}/execute",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "confirm_execution": {
    "api_route": "/api/v1/agent/intents/{intentId}/execute",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_receipt": {
    "api_route": "/api/v1/agent/receipts/{receiptId}",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_agent_activity": {
    "api_route": "/api/v1/agent/receipts",
    "feature_status_id": "agent_execution.intent_lifecycle",
    "availability": "preparation_only",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_trail_heat": {
    "api_route": "/api/v1/trail-heat",
    "feature_status_id": "trail_heat.live_scores",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "analyze_protocol_risk": {
    "api_route": "/api/v1/agent/protocol-risk",
    "feature_status_id": "trail_heat.live_scores",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_yield_strategy": {
    "api_route": "/api/v1/agent/simulate-yield",
    "feature_status_id": "trail_heat.live_scores",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "query_trail_heat": {
    "api_route": "/api/v1/agent/trail-heat-query",
    "feature_status_id": "trail_heat.live_scores",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_protocol_metadata": {
    "api_route": "/api/v1/agent/protocols",
    "feature_status_id": "protocol_intelligence.metadata",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_protocol_risk_factors": {
    "api_route": "/api/v1/agent/protocols",
    "feature_status_id": "protocol_intelligence.risk",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_chain_breakdown": {
    "api_route": "/api/v1/agent/chain-breakdown",
    "feature_status_id": "protocol_intelligence.chain",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_agent_events": {
    "api_route": "/api/v1/agent/events",
    "feature_status_id": "protocol_intelligence.events",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "audit_sybil_risk": {
    "api_route": "/api/v1/agent/sybil-audit",
    "feature_status_id": "protocol_intelligence.sybil",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_points": {
    "api_route": "/api/v1/agent/simulate-points",
    "feature_status_id": "protocol_intelligence.points",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_historical_trailheat": {
    "api_route": "/api/v1/agent/historical-trailheat",
    "feature_status_id": "trail_heat.historical",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_token_prices": {
    "api_route": "/api/v1/agent/prices",
    "feature_status_id": "protocol_intelligence.prices",
    "availability": "available",
    "tier": "scout_preview_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_wallet_balances": {
    "api_route": "/api/v1/agent/balances",
    "feature_status_id": "wallet.portfolio_reads",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_portfolio_summary": {
    "api_route": "/api/v1/agent/balances",
    "feature_status_id": "wallet.portfolio_reads",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_position_health": {
    "api_route": "/api/v1/agent/performance",
    "feature_status_id": "wallet.portfolio_reads",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_idle_capital": {
    "api_route": "/api/v1/agent/balances",
    "feature_status_id": "wallet.portfolio_reads",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "list_workflows": {
    "api_route": "/api/v1/agent/workflows",
    "feature_status_id": "workflows.supervised",
    "availability": "available_with_tier_gate",
    "tier": "scout_catalog_pioneer_runs",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "plan_workflow": {
    "api_route": "/api/v1/agent/orchestrator",
    "feature_status_id": "workflows.supervised",
    "availability": "available_with_tier_gate",
    "tier": "scout_catalog_pioneer_runs",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "run_workflow": {
    "api_route": "/api/v1/agent/orchestrator",
    "feature_status_id": "workflows.supervised",
    "availability": "available_with_tier_gate",
    "tier": "scout_catalog_pioneer_runs",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_workflow_status": {
    "api_route": "/api/v1/agent/orchestrator",
    "feature_status_id": "workflows.supervised",
    "availability": "available_with_tier_gate",
    "tier": "scout_catalog_pioneer_runs",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "find_capital_route": {
    "api_route": "/api/agents/quote",
    "feature_status_id": "swap.compatibility_evm",
    "availability": "available_with_tier_gate",
    "tier": "scout_quote_signature_and_simulation_gated",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_swap_quote": {
    "api_route": "/api/v1/agent/quote-intent",
    "feature_status_id": "swap.compatibility_evm",
    "availability": "available_with_tier_gate",
    "tier": "scout_quote_signature_and_simulation_gated",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_swap_execution": {
    "api_route": "/api/v1/simulate",
    "feature_status_id": "swap.compatibility_evm",
    "availability": "available_with_tier_gate",
    "tier": "scout_quote_signature_and_simulation_gated",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "execute_swap": {
    "api_route": "/api/agents/swap",
    "feature_status_id": "swap.compatibility_evm",
    "availability": "available_with_tier_gate",
    "tier": "scout_quote_signature_and_simulation_gated",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "confirm_swap": {
    "api_route": "/api/agents/confirm",
    "feature_status_id": "swap_fee_settlement_confirmation",
    "availability": "server_verified",
    "tier": "session_bound",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "optimize_portfolio": {
    "api_route": "/api/v1/agent/optimize-portfolio",
    "feature_status_id": "agent_planning.research",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "resolve_defi_intent": {
    "api_route": "/api/v1/agent/intent",
    "feature_status_id": "agent_planning.research",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "run_risk_sentinel": {
    "api_route": "/api/v1/agent/risk-sentinel",
    "feature_status_id": "agent_planning.research",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "compare_yields": {
    "api_route": "/api/v1/agent/supply",
    "feature_status_id": "agent_planning.research",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "recommend_delta_hedge": {
    "api_route": "/api/v1/agent/hedge",
    "feature_status_id": "agent_planning.research",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "scan_funding_rates": {
    "api_route": "/api/v1/agent/futures/scan-funding",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "scan_market_conditions": {
    "api_route": "/api/v1/agent/futures/market-conditions",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_futures_account": {
    "api_route": "/api/v1/agent/futures/account-state",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "analyze_futures_strategy": {
    "api_route": "/api/v1/agent/futures/analyze-strategy",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "calculate_position_size": {
    "api_route": "/api/v1/agent/futures/position-sizing",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "execute_perp_order": {
    "api_route": "/api/v1/agent/futures/execute-order",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "cancel_perp_order": {
    "api_route": "/api/v1/agent/futures/cancel-order",
    "feature_status_id": "futures.hyperliquid_guarded",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_research_syndicate_execution",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_agent_performance": {
    "api_route": "/api/v1/agent/performance",
    "feature_status_id": "ledger.activity",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "ledger_realized_pnl": {
    "api_route": "/api/v1/agent/ledger",
    "feature_status_id": "ledger.activity",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "ledger_tax_export": {
    "api_route": "/api/v1/agent/ledger",
    "feature_status_id": "ledger.activity",
    "availability": "paid_ready",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "audit_allowance_risk": {
    "api_route": "/api/v1/agent/camp-guard",
    "feature_status_id": "security.preflight",
    "availability": "available",
    "tier": "scout_limited_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_transaction_risk": {
    "api_route": "/api/v1/agent/camp-guard",
    "feature_status_id": "security.preflight",
    "availability": "available",
    "tier": "scout_limited_pioneer_full",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "create_session": {
    "api_route": "/api/v1/agent/session",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "session_heartbeat": {
    "api_route": "/api/v1/agent/session",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_farming_context": {
    "api_route": "/api/v1/agent/context",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "patch_farming_context": {
    "api_route": "/api/v1/agent/context",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_event_stream_snapshot": {
    "api_route": "/api/v1/agent/stream",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "verify_delegation": {
    "api_route": "/api/v1/agent/delegation",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "configure_autopilot": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "autopilot_cycle": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "pause_autopilot": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "resume_autopilot": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.sessions",
    "availability": "available_with_tier_gate",
    "tier": "pioneer_plus",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "grant_session_key": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.erc4337_submission",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "revoke_session_key": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.erc4337_submission",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "session_key_status": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.erc4337_submission",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_cycle_status": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.erc4337_submission",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "execute_cycle_actions": {
    "api_route": "/api/v1/agent/autopilot",
    "feature_status_id": "autonomous_operator.erc4337_submission",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "create_mee_intent": {
    "api_route": "/api/v1/agent/mee",
    "feature_status_id": "agent_execution.mee_cross_chain",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "simulate_mee_intent": {
    "api_route": "/api/v1/agent/mee",
    "feature_status_id": "agent_execution.mee_cross_chain",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "submit_mee_intent": {
    "api_route": "/api/v1/agent/mee",
    "feature_status_id": "agent_execution.mee_cross_chain",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_mee_intent_status": {
    "api_route": "/api/v1/agent/mee",
    "feature_status_id": "agent_execution.mee_cross_chain",
    "availability": "preparation_only",
    "tier": "syndicate",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "select_virtuals_provider_plan_v2": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "prepare_virtuals_tender_v2": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "authorize_virtuals_tender_v2": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "get_virtuals_tender": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "cancel_virtuals_tender": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "bind_virtuals_tender_job": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "reserve_virtuals_tender_funding_v2": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "record_virtuals_tender_funding_v2": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "evaluate_virtuals_tender": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  },
  "hire_virtuals_specialist": {
    "api_route": "/api/v1/agent/virtuals-acp",
    "feature_status_id": "virtuals_acp.tenant_owned_tenders",
    "availability": "available_when_deployment_prerequisites_are_met",
    "tier": "x402_or_subscription_with_authenticated_session",
    "status_endpoint": "https://www.farmdash.one/api/v1/agent/status"
  }
};

export function getMcpToolCapability(name: string): McpToolCapability {
  const capability = MCP_TOOL_CAPABILITIES[name];
  if (!capability) throw new Error(`Missing MCP capability contract for ${name}`);
  return capability;
}
